version: '3'

services:
  maildev:
    container_name: maildev
    image: djfarrelly/maildev:0.13.4
    command:
      - 'bin/maildev'
      - '--smtp'
      - '25'
    ports:
      - '1080:1080'
      - '25:25'
  mailwebapi:
    image: mailwebapi
    ports:
      - '81:80'
    build:
      context: .
      dockerfile: MailWebApi/Dockerfile
    environment:
      - TrainingSmtp=maildev